apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: build-image
      type: string
  workspaces:
    - name: output
  steps:
    - name: build
      image: buildah
      script: |
        #!/bin/bash
        buildah bud -t $(params.build-image) $(workspaces.output.path)
