apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: repository
      type: string
    - name: revision
      type: string
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.repository) $(workspaces.output.path)
        cd $(workspaces.output.path)
        git checkout $(params.revision)
