apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
spec:
  params:
    - name: app-name
      type: string
    - name: build-image
      type: string
  workspaces:
    - name: output
  steps:
    - name: deploy
      image: registry.access.redhat.com/openshift4/ose-cli
      script: |
        #!/bin/bash
        oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
